### ISSUE TITLE
Hi，请教一个关于 base64的编码直接转成readStream 的问题

### ISSUE THREAD

**Issue by femvc** [qwong/qwong.github.io#1]
Hi qwong：

你好！我在cnodejs看到你以前发的一个关于 base64的编码直接转成readStream 的帖子，试了很多次都没成功，方便分享一个简单的base64的编码直接转成readStream示例么，谢谢~~

Best wishes,
Andy

原帖如下：
https://cnodejs.org/topic/51f49b07f4963ade0e59be2d

qwong 2楼•2年前  
终于搞定了…

buffer转stream用上面仁兄给的方法或者下面这个都行

http://stackoverflow.com/questions/13230487/converting-a-buffer-into-a-readablestream-in-nodejs

可是我试了很多次都有问题，传到后台以后变成字符串了

后来跟了一下代码，发现是form-data这个中间件影响的

下面这个是form-data的源码，可以看到他是根据path来判断的，因为我们自己转的stream没有path，所以就按照普通字符串处理了…

FormData.prototype._multiPartHeader = function(field, value) {
  var boundary = this.getBoundary();
  var header =
    '--' + boundary + FormData.LINE_BREAK +
    'Content-Disposition: form-data; name="' + field + '"';

  // fs- and request- streams have path property
  // TODO: Use request's response mime-type
  if (value.path) {
    header +=
      '; filename="' + path.basename(value.path) + '"' + FormData.LINE_BREAK +
      'Content-Type: ' + mime.lookup(value.path);

  // http response has not
  } else if (value.readable && value.hasOwnProperty('httpVersion')) {
    header +=
      '; filename="' + path.basename(value.client._httpMessage.path) + '"' + FormData.LINE_BREAK +
      'Content-Type: ' + value.headers['content-type'];
  }

  header += FormData.LINE_BREAK + FormData.LINE_BREAK;
  return header;
    };

**Comment by qwong** [comment]
这都能被你找到...  :-D
不好意思啊，可能帮不到你。
我只用过不到半年nodejs，而且最近两年都没用了，所以这么细节的东西我肯定想不起来了，而且代码也早都找不到了。
抱歉。

**Comment by femvc** [comment]
感谢回复~~ 我再找找资料
